const pytaniaMaturalne = [
// ===== 2015 =====
{id:1,rok:2015,cat:"Cytologia",q:"Radioaktywnie znakowane aminokwasy podano komórkom trzustki. W jakiej kolejności znacznik pojawi się w organellach?",a:["Rybosomy → aparat Golgiego → retikulum endoplazmatyczne","Retikulum endoplazmatyczne → rybosomy → aparat Golgiego","Rybosomy → retikulum endoplazmatyczne → aparat Golgiego","Aparat Golgiego → retikulum endoplazmatyczne → rybosomy"],c:2,exp:"Białka syntetyzowane na rybosomach RER trafiają do retikulum endoplazmatycznego, a następnie do aparatu Golgiego, gdzie są modyfikowane i pakowane."},
{id:2,rok:2015,cat:"Fizjologia czlowieka",q:"Podczas intensywnego wysiłku fizycznego w mięśniach szkieletowych zachodzi fermentacja mleczanowa. Jaki jest jej bezpośredni cel?",a:["Produkcja dużej ilości ATP","Regeneracja NAD+ potrzebnego do glikolizy","Usunięcie nadmiaru pirogronianu","Produkcja kwasu mlekowego jako źródła energii"],c:1,exp:"Fermentacja mleczanowa regeneruje NAD+ z NADH, co pozwala na kontynuowanie glikolizy i produkcję ATP w warunkach beztlenowych."},
{id:3,rok:2015,cat:"Metabolizm",q:"Chemiosmoza w mitochondriach polega na:",a:["Transporcie elektronów przez błonę zewnętrzną","Przepływie protonów H+ przez syntazę ATP zgodnie z gradientem stężeń","Rozkładzie glukozy w matrix mitochondrialnej","Transporcie aktywnym jonów Na+ i K+"],c:1,exp:"W chemiosmozie protony H+ przepływają z przestrzeni międzybłonowej do matrix przez syntazę ATP, napędzając syntezę ATP."},
{id:4,rok:2015,cat:"Ekologia",q:"Jemioła pospolita jest przykładem:",a:["Saprofita","Pełnego pasożyta","Półpasożyta (hemiparasyta)","Epifita"],c:2,exp:"Jemioła jest półpasożytem - ma chlorofil i prowadzi fotosyntezę, ale pobiera wodę i sole mineralne z rośliny żywicielskiej."},
{id:5,rok:2015,cat:"Fizjologia czlowieka",q:"Które stwierdzenie o wymianie gazowej w płucach jest prawdziwe?",a:["O₂ przechodzi z krwi do pęcherzyków płucnych","CO₂ dyfunduje z pęcherzyków do krwi","Wymiana zachodzi na drodze dyfuzji zgodnie z gradientem ciśnień parcjalnych","Wymiana wymaga transportu aktywnego"],c:2,exp:"Wymiana gazowa w płucach zachodzi na zasadzie dyfuzji - gazy przemieszczają się z miejsca o wyższym ciśnieniu parcjalnym do niższego."},
{id:6,rok:2015,cat:"Immunologia",q:"Odporność czynna sztuczna jest wynikiem:",a:["Przejścia choroby zakaźnej","Podania szczepionki","Podania surowicy z przeciwciałami","Przekazania przeciwciał przez łożysko"],c:1,exp:"Szczepionka zawiera antygeny (osłabione/zabite patogeny), które stymulują układ odpornościowy do wytworzenia pamięci immunologicznej - to odporność czynna sztuczna."},
{id:7,rok:2015,cat:"Fizjologia czlowieka",q:"Autonomiczny układ nerwowy współczulny powoduje:",a:["Zwężenie źrenic i spowolnienie akcji serca","Rozszerzenie źrenic i przyspieszenie akcji serca","Nasilenie perystaltyki jelit","Obniżenie ciśnienia krwi"],c:1,exp:"Układ współczulny przygotowuje organizm do 'walcz lub uciekaj' - rozszerza źrenice, przyspiesza serce, hamuje trawienie."},
{id:8,rok:2015,cat:"Genetyka",q:"Czynnik Rh jest dziedziczony jako cecha autosomalna dominująca. Jakie genotypy mogą mieć rodzice dziecka Rh-?",a:["Oboje Rh+ (heterozygoty)","Jedno Rh+ homozygota, drugie Rh-","Oboje Rh+ homozygoty","Jedno Rh-, drugie Rh+ homozygota"],c:0,exp:"Dziecko Rh- (rr) musi otrzymać allel r od każdego rodzica. Oboje rodzice Rh+ mogą być heterozygotami (Rr × Rr → 1/4 rr)."},
{id:9,rok:2015,cat:"Botanika",q:"Fotoperiodyzm to reakcja roślin na:",a:["Intensywność światła","Długość dnia i nocy (fotoperiodem)","Kierunek padania światła","Jakość spektralną światła"],c:1,exp:"Fotoperiodyzm to reakcja organizmów na względną długość dnia i nocy, wpływająca m.in. na termin kwitnienia roślin."},
{id:10,rok:2015,cat:"Ewolucja",q:"Rośliny owadożerne wykształciły mechanizmy chwytania owadów niezależnie od siebie w różnych liniach ewolucyjnych. Jest to przykład:",a:["Dywergencji","Konwergencji","Koewolucji","Radiacji adaptacyjnej"],c:1,exp:"Niezależne wykształcenie podobnych przystosowań u niespokrewnionych organizmów to konwergencja ewolucyjna."},

// ===== 2016 =====
{id:11,rok:2016,cat:"Cytologia",q:"Mitochondria uznaje się za organella półautonomiczne, ponieważ:",a:["Mają własne DNA i rybosomy, ale potrzebują białek kodowanych w jądrze","Są całkowicie niezależne od jądra komórkowego","Nie mają własnego DNA","Powstają wyłącznie przez podział komórki"],c:0,exp:"Mitochondria mają własne koliste DNA i rybosomy (70S), ale większość ich białek jest kodowana przez DNA jądrowe - stąd określenie 'półautonomiczne'."},
{id:12,rok:2016,cat:"Metabolizm",q:"Przy zatruciu metanolem podaje się etanol, ponieważ:",a:["Etanol neutralizuje metanol chemicznie","Etanol jest inhibitorem kompetycyjnym dehydrogenazy alkoholowej","Etanol przyspiesza wydalanie metanolu","Etanol rozkłada metanol do CO₂ i H₂O"],c:1,exp:"Etanol konkuruje z metanolem o miejsce aktywne dehydrogenazy alkoholowej (inhibicja kompetycyjna), zapobiegając powstaniu toksycznego formaldehydu."},
{id:13,rok:2016,cat:"Cytologia",q:"Liposom przypomina strukturę błony komórkowej, ponieważ:",a:["Jest zbudowany z białek integralnych","Tworzy dwuwarstwę fosfolipidową","Zawiera cholesterol","Ma glikokaliks"],c:1,exp:"Liposom to sztuczny pęcherzyk otoczony dwuwarstwą fosfolipidową - podobnie jak błona komórkowa."},
{id:14,rok:2016,cat:"Botanika",q:"Auksyna powoduje wydłużanie komórek roślinnych poprzez:",a:["Hamowanie syntezy celulozy","Zakwaszanie ściany komórkowej i rozluźnianie wiązań w niej","Zwiększanie turgoru komórek","Aktywację podziałów komórkowych"],c:1,exp:"Auksyna aktywuje pompę protonową, co zakwasza ścianę komórkową. Niskie pH aktywuje ekspansyny, które rozluźniają wiązania między włóknami celulozy."},
{id:15,rok:2016,cat:"Zoologia",q:"Hormon juwenilny u owadów odpowiada za:",a:["Indukcję linienia","Utrzymywanie cech larwalnych","Indukcję metamorfozy","Stymulację rozrodu imagines"],c:1,exp:"Hormon juwenilny hamuje metamorfozę - jego wysokie stężenie utrzymuje cechy larwalne. Spadek stężenia pozwala na przeobrażenie."},
{id:16,rok:2016,cat:"Fizjologia czlowieka",q:"Hemoglobina ma większe powinowactwo do tlenu przy:",a:["Niskim pH krwi","Wysokim pH krwi","Wysokim stężeniu CO₂","Wysokiej temperaturze"],c:1,exp:"Efekt Bohra: przy niskim pH (więcej CO₂) hemoglobina łatwiej oddaje tlen. Przy wysokim pH powinowactwo do O₂ jest większe."},
{id:17,rok:2016,cat:"Genetyka",q:"W inżynierii genetycznej do produkcji ludzkiej insuliny w bakteriach używa się cDNA zamiast genu genomowego, ponieważ:",a:["cDNA jest krótsze i łatwiejsze do klonowania","cDNA nie zawiera intronów, których bakterie nie mogą wyciąć","cDNA jest bardziej stabilne","cDNA koduje więcej białka"],c:1,exp:"Bakterie nie mają aparatu do splicingu (wycinania intronów). cDNA powstaje z mRNA i nie zawiera intronów, więc bakterie mogą je prawidłowo odczytać."},
{id:18,rok:2016,cat:"Genetyka",q:"Substytucja jednego nukleotydu w genie może NIE zmienić aminokwasu w białku dzięki:",a:["Degeneracji kodu genetycznego","Uniwersalności kodu genetycznego","Kolinearności genu i białka","Nieciągłości genów eukariotycznych"],c:0,exp:"Kod genetyczny jest zdegenerowany - większość aminokwasów jest kodowana przez więcej niż jeden kodon. Zmiana w trzeciej pozycji kodonu często nie zmienia aminokwasu."},
{id:19,rok:2016,cat:"Genetyka",q:"Crossing-over zachodzi między:",a:["Chromatydami siostrzanymi jednego chromosomu","Chromatydami niesiostrzanymi chromosomów homologicznych","Chromosomami niehomologicznymi","Chromatydami siostrzanymi różnych chromosomów"],c:1,exp:"Crossing-over to wymiana fragmentów między chromatydami niesiostrzanymi chromosomów homologicznych w profazie I mejozy."},
{id:20,rok:2016,cat:"Ewolucja",q:"Dryf genetyczny może prowadzić do:",a:["Zwiększenia różnorodności genetycznej populacji","Utrwalenia niekorzystnych alleli w małej populacji","Adaptacji do środowiska","Zawsze zwiększa przystosowanie"],c:1,exp:"Dryf genetyczny to losowe zmiany częstości alleli, szczególnie silne w małych populacjach. Może prowadzić do utrwalenia nawet niekorzystnych alleli."},

// ===== 2017 =====
{id:21,rok:2017,cat:"Metabolizm",q:"Struktura III-rzędowa białka jest stabilizowana przez:",a:["Wyłącznie wiązania peptydowe","Wiązania wodorowe między grupami -CO- i -NH- łańcucha głównego","Wiązania disiarczkowe, oddziaływania hydrofobowe, jonowe i wodorowe","Wyłącznie wiązania kowalencyjne"],c:2,exp:"Strukturę III-rzędową stabilizują różne oddziaływania między łańcuchami bocznymi aminokwasów: mostki disiarczkowe, wiązania jonowe, wodorowe i oddziaływania hydrofobowe."},
{id:22,rok:2017,cat:"Botanika",q:"Heterocyty sinic Anabaena pełnią funkcję:",a:["Rozmnażania wegetatywnego","Fotosyntezy w warunkach stresu","Wiązania azotu atmosferycznego","Magazynowania substancji zapasowych"],c:2,exp:"Heterocyty to wyspecjalizowane komórki sinic, w których zachodzi wiązanie azotu atmosferycznego (N₂) dzięki enzymowi nitrogenaza."},
{id:23,rok:2017,cat:"Botanika",q:"Allelopatia polega na:",a:["Współpracy między roślinami tego samego gatunku","Wydzielaniu przez rośliny substancji hamujących wzrost innych roślin","Wzajemnym zapylaniu się roślin","Pasożytnictwie między roślinami"],c:1,exp:"Allelopatia to chemiczne oddziaływanie między roślinami - niektóre gatunki wydzielają do gleby substancje hamujące kiełkowanie lub wzrost innych roślin."},
{id:24,rok:2017,cat:"Zoologia",q:"Turkuć podjadek ma odnóża kopne przystosowane do:",a:["Skakania","Kopania w glebie","Chwytania zdobyczy","Pływania"],c:1,exp:"Turkuć podjadek (Gryllotalpa) ma silnie zmodyfikowane odnóża przednie typu kopnego, przystosowane do rycia tuneli w glebie."},
{id:25,rok:2017,cat:"Fizjologia czlowieka",q:"Synapsy elektryczne w porównaniu z chemicznymi:",a:["Przekazują impulsy wolniej","Przekazują impulsy szybciej i w obie strony","Wymagają neuroprzekaźników","Występują tylko w mózgu"],c:1,exp:"Synapsy elektryczne (koneksony/złącza szczelinowe) przewodzą impulsy szybciej niż chemiczne i mogą przewodzić dwukierunkowo."},
{id:26,rok:2017,cat:"Fizjologia czlowieka",q:"Zastawki półksiężycowate w sercu znajdują się:",a:["Między przedsionkami a komorami","U podstawy aorty i pnia płucnego","W żyłach głównych","W naczyniach wieńcowych"],c:1,exp:"Zastawki półksiężycowate (aortalna i płucna) znajdują się u ujścia aorty i pnia płucnego, zapobiegając cofaniu się krwi do komór."},
{id:27,rok:2017,cat:"Genetyka",q:"Fenyloketonuria dziedziczy się autosomalnie recesywnie. Jeśli oboje rodzice są nosicielami, prawdopodobieństwo urodzenia chorego dziecka wynosi:",a:["25%","50%","75%","100%"],c:0,exp:"Krzyżówka Aa × Aa daje: 1/4 AA, 2/4 Aa, 1/4 aa. Prawdopodobieństwo genotypu aa (chory) = 25%."},
{id:28,rok:2017,cat:"Genetyka",q:"Mutacje genów mitochondrialnych są dziedziczone:",a:["Od ojca","Od matki (dziedziczenie matczyne)","Od obojga rodziców","Nie są dziedziczone"],c:1,exp:"DNA mitochondrialne jest dziedziczone wyłącznie od matki, ponieważ mitochondria zygoty pochodzą z komórki jajowej."},
{id:29,rok:2017,cat:"Ewolucja",q:"Grupa monofiletyczna obejmuje:",a:["Wspólnego przodka i WSZYSTKICH jego potomków","Tylko niektórych potomków wspólnego przodka","Organizmy niepowiązane ewolucyjnie","Tylko organizmy żyjące współcześnie"],c:0,exp:"Grupa monofiletyczna (klad) obejmuje wspólnego przodka i wszystkich jego potomków - jest to naturalna jednostka w systematyce."},
{id:30,rok:2017,cat:"Ekologia",q:"Rozgwiazda Pisaster w eksperymencie R. Paine'a była gatunkiem zwornikowym, ponieważ jej usunięcie:",a:["Nie wpłynęło na ekosystem","Spowodowało wzrost bioróżnorodności","Drastycznie zmniejszyło liczbę gatunków w biocenozie","Zwiększyło liczbę drapieżników"],c:2,exp:"Gatunek zwornikowy (keystone species) ma nieproporcjonalnie duży wpływ na strukturę biocenozy. Usunięcie rozgwiazdy pozwoliło jednemu gatunkowi zdominować ekosystem."},

// ===== 2018 =====
{id:31,rok:2018,cat:"Cytologia",q:"W doświadczeniu osmotycznym umieszczono komórkę w roztworze hipertonicznym glukozy. Co zaobserwowano?",a:["Komórka pęczniała","Komórka uległa plazmolizie","Komórka się nie zmieniła","Komórka pękła"],c:1,exp:"W roztworze hipertonicznym woda opuszcza komórkę na drodze osmozy, co prowadzi do kurczenia się protoplazmy (plazmoliza)."},
{id:32,rok:2018,cat:"Fizjologia czlowieka",q:"Kora nadnerczy produkuje m.in. kortyzol. Komórki kory nadnerczy mają dużo:",a:["Rybosomów i szorstkiego ER","Gładkiego retikulum endoplazmatycznego i kropli lipidowych","Lizosomów","Chloroplastów"],c:1,exp:"Hormony steroidowe (jak kortyzol) są syntezowane z cholesterolu na gładkim ER. Kropelki lipidowe magazynują cholesterol - substrat do syntezy."},
{id:33,rok:2018,cat:"Metabolizm",q:"Kolagen traci swoją strukturę przy niedoborze witaminy C, ponieważ:",a:["Witamina C jest potrzebna do hydroksylacji proliny i lizyny w kolagenie","Witamina C buduje łańcuch kolagenu","Witamina C chroni kolagen przed utlenieniem","Brak witaminy C powoduje mutacje w genie kolagenu"],c:0,exp:"Witamina C jest kofaktorem hydroksylazy prolinowej i lizylowej. Bez niej kolagen nie tworzy prawidłowej struktury potrójnej helisy - to przyczyna szkorbutu."},
{id:34,rok:2018,cat:"Metabolizm",q:"Termogenina w brunatnej tkance tłuszczowej działa jako:",a:["Enzym rozkładający tłuszcze","Białko rozprzęgające łańcuch oddechowy od syntezy ATP","Transporter glukozy","Receptor insuliny"],c:1,exp:"Termogenina (UCP1) tworzy kanał dla protonów w wewnętrznej błonie mitochondrialnej, omijając syntazę ATP. Energia gradientu jest zamieniana na ciepło."},
{id:35,rok:2018,cat:"Zoologia",q:"Głowonogi (np. ośmiornice) mają zamknięty układ krążenia, co oznacza, że:",a:["Krew nigdy nie opuszcza naczyń krwionośnych","Krew wpływa do zatok ciała","Mają tylko jedno serce","Nie mają hemocyjaniny"],c:0,exp:"W zamkniętym układzie krążenia krew krąży wyłącznie w naczyniach krwionośnych (tętnice → naczynia włosowate → żyły), co zapewnia wydajniejszy transport."},
{id:36,rok:2018,cat:"Fizjologia czlowieka",q:"Choroba Gravesa-Basedowa jest chorobą autoimmunologiczną, w której przeciwciała:",a:["Niszczą komórki tarczycy","Stymulują receptor TSH na tarczycy, powodując nadczynność","Blokują wydzielanie TSH z przysadki","Niszczą jod w tarczycy"],c:1,exp:"W chorobie Gravesa przeciwciała naśladują TSH i stymulują tarczycę do nadmiernej produkcji hormonów T3/T4."},
{id:37,rok:2018,cat:"Metabolizm",q:"Metotreksat jest inhibitorem kompetycyjnym reduktazy dihydrofolianowej. Hamuje on:",a:["Syntezę lipidów","Syntezę nukleotydów (replikację DNA)","Syntezę białek na rybosomach","Transport jonów przez błonę"],c:1,exp:"Kwas foliowy jest kofaktorem w syntezie nukleotydów. Metotreksat blokuje jego aktywację, hamując podział komórek - dlatego jest stosowany w chemioterapii."},
{id:38,rok:2018,cat:"Genetyka",q:"Acetylacja histonów prowadzi do:",a:["Skondensowania chromatyny i zahamowania transkrypcji","Rozluźnienia chromatyny i ułatwienia transkrypcji","Replikacji DNA","Mutacji genowych"],c:1,exp:"Acetylacja neutralizuje ładunek dodatni histonów, osłabiając ich wiązanie z DNA (ładunek ujemny). Chromatyna się rozluźnia, umożliwiając transkrypcję."},
{id:39,rok:2018,cat:"Genetyka",q:"U kotów gen barwy sierści ma allele: Cᴬ (agouti), cᵇ (czarny), c (rudy). Seria alleli oznacza, że:",a:["Każdy osobnik ma wszystkie trzy allele","W populacji istnieje więcej niż 2 allele jednego genu, ale osobnik ma najwyżej 2","Geny znajdują się na różnych chromosomach","Allele nie podlegają prawom Mendla"],c:1,exp:"Seria alleli (allele wielokrotne) oznacza, że w populacji istnieją więcej niż 2 warianty jednego genu, ale diploidalny osobnik posiada co najwyżej 2 allele."},
{id:40,rok:2018,cat:"Ekologia",q:"Bioakumulacja PCB (polichlorowanych bifenyli) w łańcuchu pokarmowym oznacza, że:",a:["Stężenie PCB maleje na kolejnych poziomach troficznych","Stężenie PCB rośnie na kolejnych poziomach troficznych","PCB jest rozkładane przez destruentów","PCB nie wchodzi do łańcuchów pokarmowych"],c:1,exp:"Bioakumulacja (biomagnifikacja) oznacza, że trwałe zanieczyszczenia kumulują się w organizmach i ich stężenie rośnie z każdym poziomem troficznym."},

// ===== 2019 =====
{id:41,rok:2019,cat:"Cytologia",q:"Jąderko jest miejscem:",a:["Replikacji DNA","Syntezy rRNA i składania podjednostek rybosomów","Transkrypcji mRNA","Obróbki post-translacyjnej białek"],c:1,exp:"W jąderku zachodzi transkrypcja genów rRNA oraz składanie podjednostek rybosomalnych z rRNA i białek rybosomalnych."},
{id:42,rok:2019,cat:"Metabolizm",q:"Fosforylacja niecykliczna różni się od cyklicznej tym, że:",a:["Nie produkuje ATP","Zachodzi bez udziału światła","Wytwarza zarówno ATP, NADPH jak i O₂","Zachodzi wyłącznie w mitochondriach"],c:2,exp:"Fosforylacja niecykliczna angażuje oba fotosystemy (I i II), produkuje ATP, NADPH i O₂ (z fotolizy wody). Cykliczna produkuje tylko ATP."},
{id:43,rok:2019,cat:"Botanika",q:"Fitochrom to białko roślinne, które:",a:["Transportuje wodę w ksylemie","Jest receptorem światła czerwonego i reguluje fotoperiodyzm","Odpowiada za fotosyntezę","Jest hormonem wzrostu"],c:1,exp:"Fitochrom istnieje w dwóch formach (Pr i Pfr) i jest receptorem światła czerwonego i dalekiej czerwieni. Reguluje m.in. kwitnienie i kiełkowanie."},
{id:44,rok:2019,cat:"Botanika",q:"Kwas abscysynowy (ABA) powoduje:",a:["Wydłużanie komórek łodygi","Zamykanie aparatów szparkowych i hamowanie wzrostu","Dojrzewanie owoców","Indukowanie podziałów komórkowych"],c:1,exp:"ABA jest hormonem stresu - powoduje zamykanie szparek (ochrona przed utratą wody), hamuje wzrost i indukuje spoczynek nasion."},
{id:45,rok:2019,cat:"Mikrobiologia",q:"Terapia fagowa polega na wykorzystaniu:",a:["Antybiotyków przeciwko bakteriom","Bakteriofagów do zabijania bakterii chorobotwórczych","Grzybów do zwalczania bakterii","Promieniowania UV do sterylizacji"],c:1,exp:"Terapia fagowa wykorzystuje bakteriofagi (wirusy atakujące bakterie) jako alternatywę dla antybiotyków w leczeniu infekcji bakteryjnych."},
{id:46,rok:2019,cat:"Immunologia",q:"Przeciwciało (immunoglobulina) składa się z:",a:["Jednego łańcucha polipeptydowego","Dwóch łańcuchów ciężkich i dwóch lekkich połączonych mostkami disiarczkowymi","Czterech identycznych łańcuchów","Kwasów nukleinowych i białek"],c:1,exp:"Przeciwciało ma strukturę Y - 2 łańcuchy ciężkie (H) i 2 lekkie (L) połączone wiązaniami disiarczkowymi. Fragmenty Fab wiążą antygen, Fc aktywuje układ odpornościowy."},
{id:47,rok:2019,cat:"Genetyka",q:"Prawo Hardy'ego-Weinberga mówi, że częstości alleli w populacji pozostają stałe, gdy:",a:["Populacja jest mała i izolowana","Zachodzi dobór naturalny","Populacja jest duża, krzyżowanie losowe, brak mutacji, migracji i doboru","Zachodzą częste mutacje"],c:2,exp:"Równowaga Hardy'ego-Weinberga wymaga: dużej populacji, losowego krzyżowania, braku mutacji, migracji, dryfu i doboru naturalnego. p² + 2pq + q² = 1."},
{id:48,rok:2019,cat:"Genetyka",q:"Operon tryptofanowy u E. coli jest regulowany przez:",a:["Indukcję - włączany przez tryptofan","Represję - wyłączany gdy tryptofan (korepresor) wiąże się z represorem","Zawsze jest aktywny","Regulację pozytywną przez aktywator"],c:1,exp:"Operon trp jest regulowany przez represję. Gdy tryptofan jest w nadmiarze, wiąże się z represorem (białko regulatorowe), który blokuje transkrypcję."},
{id:49,rok:2019,cat:"Ekologia",q:"Zmienność fenotypowa danej cechy może być:",a:["Tylko genetyczna","Tylko środowiskowa","Genetyczna, środowiskowa lub obu typów jednocześnie","Niezależna od genów i środowiska"],c:2,exp:"Fenotyp jest wynikiem interakcji genotypu i środowiska. Zmienność fenotypowa może wynikać z różnic genetycznych, środowiskowych lub ich kombinacji."},
{id:50,rok:2019,cat:"Ewolucja",q:"Karpieniec diabelski (Cyprinodon diabolis) żyje wyłącznie w jednym źródle w Nevadzie. Jest to przykład:",a:["Specjacji sympatrycznej","Specjacji allopatrycznej","Dryfu genetycznego","Doboru kierunkowego"],c:1,exp:"Izolacja geograficzna małej populacji w jednym źródle doprowadziła do powstania odrębnego gatunku - to klasyczny przykład specjacji allopatrycznej."},

// ===== 2020 =====
{id:51,rok:2020,cat:"Cytologia",q:"Model płynnej mozaiki błony komórkowej zakłada, że:",a:["Białka są trwale związane z fosfolipidami","Fosfolipidy i białka mogą przemieszczać się lateralnie w płaszczyźnie błony","Błona jest sztywną strukturą","Cholesterol nie jest składnikiem błony"],c:1,exp:"Model płynnej mozaiki Singera i Nicolsona mówi, że białka 'pływają' w dwuwarstwie fosfolipidowej, a składniki mogą się przemieszczać lateralnie."},
{id:52,rok:2020,cat:"Histologia",q:"Fibroblasty są komórkami:",a:["Tkanki nabłonkowej","Tkanki łącznej właściwej, produkującymi kolagen","Tkanki mięśniowej","Tkanki nerwowej"],c:1,exp:"Fibroblasty to główne komórki tkanki łącznej właściwej - produkują składniki macierzy zewnątrzkomórkowej, w tym kolagen i elastynę."},
{id:53,rok:2020,cat:"Botanika",q:"Aerenchyma (tkanka powietrzna) u roślin wodnych służy do:",a:["Magazynowania wody","Transportu gazów i utrzymywania pływalności","Fotosyntezy","Ochrony przed patogenami"],c:1,exp:"Aerenchyma zawiera duże przestrzenie międzykomórkowe wypełnione powietrzem, co ułatwia transport gazów do korzeni zanurzonych i zapewnia pływalność."},
{id:54,rok:2020,cat:"Botanika",q:"Rzodkiewnik pospolity (Arabidopsis thaliana) jest organizmem modelowym w genetyce roślin, ponieważ:",a:["Ma duży genom i długi cykl życiowy","Ma mały genom, krótki cykl życiowy i łatwo się go hoduje","Jest rośliną użytkową","Ma tylko 2 chromosomy"],c:1,exp:"Arabidopsis ma mały genom (~135 Mpz), krótki cykl życiowy (6 tyg.), łatwo się go transformuje genetycznie i jest dobrze poznany."},
{id:55,rok:2020,cat:"Fizjologia czlowieka",q:"Surfaktant w pęcherzykach płucnych:",a:["Transportuje tlen do krwi","Zmniejsza napięcie powierzchniowe, zapobiegając zapadaniu się pęcherzyków","Neutralizuje patogeny","Zwiększa produkcję śluzu"],c:1,exp:"Surfaktant (mieszanina fosfolipidów) zmniejsza napięcie powierzchniowe na granicy powietrze-płyn w pęcherzykach, zapobiegając ich zapadaniu przy wydechu."},
{id:56,rok:2020,cat:"Fizjologia czlowieka",q:"Inulina jest używana do pomiaru filtracji kłębuszkowej (GFR), ponieważ:",a:["Jest rozkładana w kanalikach nerkowych","Jest swobodnie filtrowana, ale nie jest ani wchłaniana, ani wydzielana w kanalikach","Nie jest filtrowana w kłębuszkach","Jest syntetyzowana w nerkach"],c:1,exp:"Inulina jest idealnym markerem GFR - przechodzi swobodnie przez filtr kłębuszkowy i nie podlega reabsorpcji ani sekrecji w kanalikach nerkowych."},
{id:57,rok:2020,cat:"Fizjologia czlowieka",q:"Termoregulacja u człowieka w wysokiej temperaturze obejmuje:",a:["Skurcz naczyń krwionośnych skóry","Rozszerzenie naczyń skóry i wzmożone pocenie","Drżenie mięśniowe","Wzrost metabolizmu"],c:1,exp:"W gorącu naczynia skóry rozszerzają się (zwiększając utratę ciepła przez promieniowanie), a gruczoły potowe wydzielają pot (utrata ciepła przez parowanie)."},
{id:58,rok:2020,cat:"Genetyka",q:"Nietolerancja laktozy u dorosłych jest cechą dziedziczoną autosomalnie recesywnie. Oznacza to, że:",a:["Wystarczy jeden allel dominujący, by trawić laktozę","Oboje rodzice muszą być nietolerantni","Gen znajduje się na chromosomie X","Laktoza nie jest cukrem"],c:0,exp:"Przy dziedziczeniu autosomalnym recesywnym, osoby z jednym allelem dominującym (Ll) i z dwoma (LL) trawią laktozę. Tylko homozygoty recesywne (ll) są nietolerancyjne."},
{id:59,rok:2020,cat:"Genetyka",q:"System naprawy DNA przez wycinanie nukleotydów (NER) służy do:",a:["Replikacji DNA","Usuwania uszkodzeń DNA (np. dimerów tyminy) i zastępowania prawidłowymi nukleotydami","Transkrypcji genów","Rekombinacji genetycznej"],c:1,exp:"NER rozpoznaje zniekształcenia helisy DNA (np. dimery tyminowe po UV), wycina uszkodzony fragment i zastępuje go prawidłową sekwencją."},
{id:60,rok:2020,cat:"Ekologia",q:"Kolonizacja wyspy wulkanicznej Surtsey (Islandia) jest przykładem:",a:["Sukcesji wtórnej","Sukcesji pierwotnej","Klimaksu ekologicznego","Eutrofizacji"],c:1,exp:"Surtsey powstała w 1963 r. Kolonizacja nagiego terenu wulkanicznego od zera to sukcesja pierwotna - od porostów, przez mszaki, do roślin naczyniowych."},

// ===== 2021 =====
{id:61,rok:2021,cat:"Metabolizm",q:"W łańcuchu oddechowym gradient protonowy jest wytwarzany po:",a:["Zewnętrznej stronie wewnętrznej błony mitochondrialnej (przestrzeń międzybłonowa)","Wewnątrz matrix mitochondrialnej","Na zewnętrznej błonie mitochondrialnej","W cytoplazmie"],c:0,exp:"Kompleksy I, III i IV pompują protony z matrix do przestrzeni międzybłonowej, tworząc gradient elektrochemiczny napędzający syntazę ATP."},
{id:62,rok:2021,cat:"Metabolizm",q:"L-kanawanina jest aminokwasem roślinnym podobnym do argininy. Może być szkodliwa dla roślinożerców, ponieważ:",a:["Jest toksycznym metalem ciężkim","Może być wbudowywana do białek zamiast argininy, zaburzając ich funkcję","Blokuje fotosyntezę","Niszczy DNA"],c:1,exp:"L-kanawanina jest analogiem argininy - może być wbudowywana do białek przez syntetazę aminoacylo-tRNA, powodując powstanie nieprawidłowych białek."},
{id:63,rok:2021,cat:"Cytologia",q:"Glikokaliks na erytrocytach pełni funkcję:",a:["Transportu tlenu","Określania grupy krwi (zawiera antygeny grupowe)","Syntezy hemoglobiny","Fagocytozy"],c:1,exp:"Glikokaliks erytrocytów zawiera glikoproteiny i glikolipidy tworzące antygeny grupowe (A, B lub brak w grupie 0)."},
{id:64,rok:2021,cat:"Botanika",q:"Etylen u roślin pełni rolę:",a:["Stymulowania wzrostu łodygi","Przyspieszania dojrzewania owoców i starzenia się liści","Indukowania kiełkowania nasion","Stymulowania fotosyntezy"],c:1,exp:"Etylen jest gazowym hormonem przyspieszającym dojrzewanie owoców, opadanie liści (absycja) i starzenie się tkanek roślinnych."},
{id:65,rok:2021,cat:"Fizjologia czlowieka",q:"Potencjał czynnościowy neuronu podlega zasadzie 'wszystko albo nic', co oznacza:",a:["Impuls może mieć różną amplitudę","Impuls zawsze ma taką samą amplitudę, niezależnie od siły bodźca nadprogowego","Neuron nie reaguje na żadne bodźce","Wszystkie synapsy są jednakowo aktywne"],c:1,exp:"Po przekroczeniu progu pobudzenia impuls nerwowy ma zawsze taką samą amplitudę - siła bodźca jest kodowana częstotliwością impulsów, nie ich wielkością."},
{id:66,rok:2021,cat:"Fizjologia czlowieka",q:"Trzustka wydziela enzymy trawienne w formie nieaktywnej (zymogeny), aby:",a:["Zaoszczędzić energię","Zapobiec trawieniu własnych tkanek trzustki","Zwiększyć szybkość trawienia","Umożliwić transport enzymów przez krew"],c:1,exp:"Zymogeny (np. trypsynogen) są nieaktywne w trzustce, by zapobiec samoprokwięciu. Aktywują się dopiero w dwunastnicy - enterokinaza aktywuje trypsynogen do trypsyny."},
{id:67,rok:2021,cat:"Zoologia",q:"Strusie afrykańskie produkują mocz o wysokiej osmolalności, co jest przystosowaniem do:",a:["Środowiska wodnego","Życia w środowisku o ograniczonej dostępności wody","Życia na dużych wysokościach","Niskiej temperatury"],c:1,exp:"Wysoka osmolalność moczu oznacza silne zagęszczanie - nerki odzyskują więcej wody. To adaptacja do życia w suchych siedliskach (oszczędność wody)."},
{id:68,rok:2021,cat:"Genetyka",q:"Introny są wycinane z pre-mRNA w procesie:",a:["Replikacji","Translacji","Splicingu","Odwrotnej transkrypcji"],c:2,exp:"Splicing to obróbka post-transkrypcyjna, w której spliceosomy wycinają introny z pre-mRNA i łączą eksony w dojrzały mRNA."},
{id:69,rok:2021,cat:"Ewolucja",q:"Lotopałanki (ssaki torbacze) i polatuchy (ssaki łożyskowe) mają skórzaste fałdy umożliwiające szybowanie. Ich 'skrzydła' to narządy:",a:["Homologiczne","Analogiczne (powstałe w wyniku konwergencji)","Rudymentalne","Atawistyczne"],c:1,exp:"Niespokrewnione grupy ssaków niezależnie wykształciły fałdy do szybowania - to konwergencja ewolucyjna. Narządy analogiczne mają różne pochodzenie."},
{id:70,rok:2021,cat:"Ekologia",q:"Eutrofizacja zbiornika wodnego prowadzi kolejno do:",a:["Spadku tlenu → zakwitu glonów → śmierci ryb","Zakwitu glonów → rozkładu martwej materii → spadku tlenu → śmierci ryb","Wzrostu populacji ryb → zakwitu glonów → wzrostu tlenu","Spadku nutrientów → spadku glonów → wzrostu ryb"],c:1,exp:"Nadmiar nutrientów → zakwit glonów → obumarcie glonów → rozkład przez bakterie zużywające tlen → deficyt tlenu → śmierć organizmów."},

// ===== 2022 =====
{id:71,rok:2022,cat:"Cytologia",q:"Transport aktywny przez błonę komórkową wymaga:",a:["Wyłącznie gradientu stężeń","Energii (ATP) i białek transportujących","Endocytozy","Wyłącznie dyfuzji"],c:1,exp:"Transport aktywny przenosi substancje wbrew gradientowi stężeń, co wymaga nakładu energii (ATP) i specyficznych białek nośnikowych lub pomp."},
{id:72,rok:2022,cat:"Fizjologia czlowieka",q:"Insulina obniża poziom glukozy we krwi m.in. poprzez:",a:["Hamowanie wychwytu glukozy przez komórki","Stymulowanie wbudowywania transporterów GLUT4 w błony komórek mięśniowych i tłuszczowych","Rozkładanie glikogenu w wątrobie","Hamowanie syntezy glikogenu"],c:1,exp:"Insulina stymuluje translokację transporterów GLUT4 z pęcherzyków cytoplazmatycznych do błony komórkowej, zwiększając wychwyt glukozy."},
{id:73,rok:2022,cat:"Fizjologia czlowieka",q:"Wazopresyna (ADH) powoduje:",a:["Zwiększenie objętości moczu","Zwiększenie reabsorpcji wody w kanalikach zbiorczych nerek","Rozszerzenie naczyń nerkowych","Zmniejszenie reabsorpcji sodu"],c:1,exp:"ADH zwiększa przepuszczalność kanalików zbiorczych dla wody (przez wbudowanie akwaporyn), co prowadzi do reabsorpcji wody i zagęszczenia moczu."},
{id:74,rok:2022,cat:"Genetyka",q:"Translokacja chromosomów Philadelphia (t9;22) w białaczce szpikowej powoduje:",a:["Utratę całego chromosomu","Powstanie fuzyjnego genu BCR-ABL kodującego konstytutywnie aktywną kinazę tyrozynową","Trisomię chromosomu 22","Delecję genów supresorowych"],c:1,exp:"Translokacja t(9;22) łączy gen BCR z ABL, tworząc onkogen kodujący stale aktywną kinazę, która stymuluje niekontrolowane podziały komórek."},
{id:75,rok:2022,cat:"Metabolizm",q:"Podczas glikolizy jedna cząsteczka glukozy jest przekształcana w:",a:["1 cząsteczkę pirogronianu","2 cząsteczki pirogronianu + 2 ATP + 2 NADH","6 cząsteczek CO₂ i 6 H₂O","1 cząsteczkę kwasu mlekowego"],c:1,exp:"Glikoliza przekształca 1 glukozę (6C) w 2 pirogroniany (3C), produkując netto 2 ATP i 2 NADH. Zachodzi w cytoplazmie."},
{id:76,rok:2022,cat:"Botanika",q:"Floem (łyko) transportuje:",a:["Wodę i sole mineralne z korzeni do liści","Asymilaty (głównie sacharozę) z liści do innych części rośliny","Tylko auksyny","Gazy oddechowe"],c:1,exp:"Floem transportuje produkty fotosyntezy (głównie sacharozę) z miejsc produkcji (liście) do miejsc zapotrzebowania (korzenie, owoce, pędy) - transport bliższy."},
{id:77,rok:2022,cat:"Ekologia",q:"Gatunek inwazyjny to gatunek, który:",a:["Pochodzi z danego ekosystemu","Jest obcy dla ekosystemu i zagraża rodzimej bioróżnorodności","Zawsze jest chroniony prawem","Jest rzadki i zagrożony wyginięciem"],c:1,exp:"Gatunek inwazyjny to gatunek obcego pochodzenia, który rozprzestrzenia się i zagraża lokalnej bioróżnorodności, gospodarce lub zdrowiu ludzi."},
{id:78,rok:2022,cat:"Immunologia",q:"Odpowiedź immunologiczna typu alergicznego angażuje głównie:",a:["Limfocyty T cytotoksyczne","Przeciwciała IgE i komórki tuczne (mastocyty)","Limfocyty B pamięci","Makrofagi i neutrofile"],c:1,exp:"W alergii alergen wiąże się z IgE na komórkach tucznych, powodując ich degranulację i uwolnienie histaminy oraz innych mediatorów zapalenia."},
{id:79,rok:2022,cat:"Fizjologia czlowieka",q:"Cukrzyca typu 1 jest spowodowana:",a:["Opornością komórek na insulinę","Autoimmunologicznym zniszczeniem komórek beta wysp Langerhansa","Nadmierną produkcją insuliny","Niedoborem glukagonu"],c:1,exp:"W cukrzycy typu 1 układ odpornościowy niszczy komórki beta trzustki, co prowadzi do niedoboru insuliny i hiperglikemii."},
{id:80,rok:2022,cat:"Ewolucja",q:"Dobór kierunkowy powoduje:",a:["Eliminację form skrajnych","Przesunięcie średniej wartości cechy w jednym kierunku","Utrzymanie średniej cechy bez zmian","Powstanie dwóch szczytów w rozkładzie cechy"],c:1,exp:"Dobór kierunkowy faworyzuje jedną wartość skrajną cechy, przesuwając średnią populacji w tym kierunku (np. zwiększanie rozmiaru ciała)."},

// ===== 2023 =====
{id:81,rok:2023,cat:"Metabolizm",q:"Kompleks dehydrogenazy pirogronianowej łączy:",a:["Cykl Calvina z fazą jasną fotosyntezy","Glikolizę z cyklem Krebsa, przekształcając pirogronian w acetylo-CoA","Łańcuch oddechowy z fosforylacją oksydacyjną","Beta-oksydację z glikolizą"],c:1,exp:"Dehydrogenaza pirogronianowa dekarboksyluje pirogronian do acetylo-CoA w matrix mitochondrialnej, łącząc glikolizę z cyklem Krebsa."},
{id:82,rok:2023,cat:"Metabolizm",q:"RuBisCO (karboksylaza/oksygenaza rybulozo-1,5-bisfosforanu) może wiązać zarówno CO₂ jak i O₂. Gdy wiąże O₂, zachodzi:",a:["Fotosynteza C4","Fotooddychanie, zmniejszające wydajność fotosyntezy","Fermentacja","Chemosynteza"],c:1,exp:"Fotooddychanie to nieproduktywny proces, w którym RuBisCO wiąże O₂ zamiast CO₂, produkując glikolian. Zmniejsza wydajność fotosyntezy o 25-30%."},
{id:83,rok:2023,cat:"Botanika",q:"Rośliny C4 (np. kukurydza) radzą sobie z fotooddychaniem dzięki:",a:["Otwieraniu szparek tylko w nocy","Wstępnemu wiązaniu CO₂ przez PEP-karboksylazę w komórkach mezofilu, a następnie przekazaniu go do cyklu Calvina w komórkach pochew wiązek","Brakowi RuBisCO","Ograniczeniu fotosyntezy do korzeni"],c:1,exp:"U roślin C4 PEP-karboksylaza (nie wiąże O₂) wstępnie wiąże CO₂ w komórkach mezofilu. CO₂ jest uwalniane i zagęszczane w komórkach pochew wiązek, gdzie działa RuBisCO."},
{id:84,rok:2023,cat:"Fizjologia czlowieka",q:"Toksyna botulinowa działa na złącze nerwowo-mięśniowe poprzez:",a:["Stymulowanie wydzielania acetylocholiny","Blokowanie uwalniania acetylocholiny z zakończenia nerwowego","Niszczenie receptorów acetylocholinowych","Hamowanie rozkładu acetylocholiny"],c:1,exp:"Toksyna botulinowa (botulina) hamuje uwalnianie acetylocholiny z pęcherzyków synaptycznych, uniemożliwiając przekazanie impulsu do mięśnia - powoduje porażenie wiotkie."},
{id:85,rok:2023,cat:"Genetyka",q:"W metodzie PCR (łańcuchowa reakcja polimerazy) startery (primery) są potrzebne, aby:",a:["Rozdzielić nici DNA","Dostarczyć miejsce startu dla polimerazy DNA","Oznaczyć fluorescencyjnie produkt","Wyciąć fragment genu"],c:1,exp:"Startery to krótkie oligonukleotydy komplementarne do sekwencji flankujących amplifikowany fragment. Polimeraza DNA potrzebuje startera jako miejsca inicjacji syntezy."},
{id:86,rok:2023,cat:"Genetyka",q:"U labradorów barwa sierści jest determinowana przez 2 geny: gen E (warunkuje odkładanie pigmentu) i gen B (typ pigmentu). Czarny labrador o genotypie BbEe skrzyżowany z żółtym (BBee) może dać potomstwo:",a:["Tylko czarne","Tylko żółte","Czarne i żółte","Czarne, brązowe i żółte"],c:2,exp:"BbEe × BBee → potomstwo: BBEe (czarny), BbEe (czarny), BBee (żółty), Bbee (żółty). Stosunek 1:1 czarny:żółty. Brązowy wymaga bb."},
{id:87,rok:2023,cat:"Ekologia",q:"Wargatek czyściciel (Labroides dimidiatus) zjada pasożyty z ciała większych ryb. Ta relacja to:",a:["Komensalizm","Mutualizm (protokooperacja)","Parazytyzm","Konkurencja"],c:1,exp:"Obie strony odnoszą korzyści: wargatek zyskuje pokarm, a ryba-klient pozbywa się pasożytów. To mutualizm (współpraca obopólnie korzystna)."},
{id:88,rok:2023,cat:"Ekologia",q:"Murawy kserotermiczne wymagają ochrony czynnej, polegającej m.in. na:",a:["Całkowitym zakazie wstępu ludzi","Kontrolowanym wypasie lub koszeniu, zapobiegającym sukcesji","Nawadnianiu i nawożeniu","Zalesianiu terenu"],c:1,exp:"Murawy kserotermiczne to półnaturalne zbiorowiska utrzymywane przez wypas/koszenie. Bez ochrony czynnej zarastają krzewami i drzewami (sukcesja)."},
{id:89,rok:2023,cat:"Fizjologia czlowieka",q:"2,3-bisfosfoglicerynian (2,3-BPG) w erytrocytach:",a:["Zwiększa powinowactwo hemoglobiny do tlenu","Zmniejsza powinowactwo hemoglobiny do tlenu, ułatwiając jego oddawanie tkankom","Transportuje CO₂","Jest substratem glikolizy"],c:1,exp:"2,3-BPG wiąże się z deoksyhemoglobiną, stabilizując ją i zmniejszając powinowactwo do O₂. Ułatwia to oddawanie tlenu tkankom."},
{id:90,rok:2023,cat:"Zoologia",q:"Amfisbeny (dwużyjki) są:",a:["Płazami bezogonowymi","Gadami z silnie zredukowanymi lub brakiem kończyn, prowadzącymi podziemny tryb życia","Rybami bezszczękowymi","Stawonogami"],c:1,exp:"Amfisbeny to gady (Squamata) z ciałem walcowatym i zredukowanymi kończynami, przystosowane do życia w glebie - mogą poruszać się do przodu i do tyłu."},

// ===== 2024 =====
{id:91,rok:2024,cat:"Mikrobiologia",q:"Odwrotna transkryptaza HIV jest enzymem, który:",a:["Przepisuje DNA na RNA","Przepisuje RNA wirusa na DNA, które wbudowuje się w genom gospodarza","Rozkłada białka wirusa","Replikuje DNA wirusa"],c:1,exp:"Odwrotna transkryptaza retrowirusów (jak HIV) przepisuje RNA wirusa na DNA (odwrotna transkrypcja), które integraza wbudowuje w DNA gospodarza."},
{id:92,rok:2024,cat:"Zoologia",q:"Bioluminescencja u świetlików jest możliwa dzięki reakcji:",a:["Fotosyntezy","Oksydacji lucyferyny katalizowanej przez lucyferazę","Fosforylacji oksydacyjnej","Chemosmozy"],c:1,exp:"Bioluminescencja to utlenianie lucyferyny przez enzym lucyferazę w obecności ATP i O₂, dające emisję światła."},
{id:93,rok:2024,cat:"Fizjologia czlowieka",q:"Blokada kanałów sodowych bramkowanych napięciem w neuronie spowoduje:",a:["Silniejszy potencjał czynnościowy","Brak możliwości wygenerowania potencjału czynnościowego (faza depolaryzacji)","Ciągłą depolaryzację","Zwiększoną częstotliwość impulsów"],c:1,exp:"Depolaryzacja zależy od napływu Na+ przez kanały bramkowane napięciem. Ich blokada uniemożliwia wygenerowanie potencjału czynnościowego."},
{id:94,rok:2024,cat:"Genetyka",q:"Choroby mitochondrialne są dziedziczone w linii matczynej i dotykają narządów o dużym zapotrzebowaniu energetycznym, takich jak:",a:["Skóra i paznokcie","Mięśnie, mózg i serce","Kości i chrząstki","Tkanka tłuszczowa"],c:1,exp:"Mutacje mtDNA zaburzają fosforylację oksydacyjną. Najbardziej cierpią tkanki o wysokim zapotrzebowaniu na ATP: mięśnie szkieletowe, serce, mózg, nerki."},
{id:95,rok:2024,cat:"Genetyka",q:"tRNA pełni funkcję:",a:["Magazynu informacji genetycznej","Adaptera łączącego kodon mRNA z odpowiednim aminokwasem podczas translacji","Enzymu wycinającego introny","Składnika rybosomów"],c:1,exp:"tRNA ma antykodon komplementarny do kodonu mRNA i przenosi odpowiedni aminokwas. Jest 'tłumaczem' między językiem kwasów nukleinowych a białek."},
{id:96,rok:2024,cat:"Ekologia",q:"Spadek liczebności płazów na świecie jest związany m.in. z:",a:["Wzrostem populacji owadów","Utratą siedlisk, chorobą chytridiomykozą i zanieczyszczeniem wód","Nadmiernym wzrostem populacji płazów","Brakiem drapieżników"],c:1,exp:"Płazy są zagrożone przez: niszczenie mokradeł, grzyba Batrachochytrium dendrobatidis (chytridiomykoza), zanieczyszczenia, zmianę klimatu i promieniowanie UV."},
{id:97,rok:2024,cat:"Botanika",q:"Kambium naczyniowe jest tkanką twórczą boczną odpowiedzialną za:",a:["Wzrost na długość","Wzrost na grubość (przyrost wtórny łodygi i korzenia)","Fotosyntezę","Transport wody"],c:1,exp:"Kambium waskularnie dzieli się, produkując ksylem wtórny (do wewnątrz) i floem wtórny (na zewnątrz), powodując przyrost na grubość."},
{id:98,rok:2024,cat:"Immunologia",q:"Roztocza kurzu domowego wytwarzają alergeny, które u osób uczulonych powodują reakcję z udziałem:",a:["Limfocytów T cytotoksycznych","Immunoglobulin klasy IgE i histaminy","Dopełniacza","Interferonów"],c:1,exp:"Alergeny roztoczy aktywują komórki tuczne opłaszczone IgE, prowadząc do degranulacji i uwolnienia histaminy - mediator objawów alergicznych."},

// ===== 2025 =====
{id:99,rok:2025,cat:"Metabolizm",q:"Denaturacja białka oznacza:",a:["Zmianę sekwencji aminokwasów","Utratę struktury wyższego rzędu (II, III, IV) bez zerwania wiązań peptydowych","Hydrolizę wiązań peptydowych","Syntezę nowego białka"],c:1,exp:"Denaturacja to utrata natywnej konformacji białka (rozwinięcie struktury) pod wpływem temperatury, pH itp. Wiązania peptydowe i sekwencja (I-rzędowa) pozostają nienaruszone."},
{id:100,rok:2025,cat:"Cytologia",q:"Chromoplasty powstają z chloroplastów podczas:",a:["Fotosyntezy","Dojrzewania owoców (zmiana barwy z zielonej na żółtą/czerwoną)","Oddychania komórkowego","Podziału komórki"],c:1,exp:"Podczas dojrzewania owoców chloroplasty tracą chlorofil i gromadzą karotenoidy, przekształcając się w chromoplasty - stąd zmiana barwy."},
{id:101,rok:2025,cat:"Botanika",q:"Geotropizm dodatni korzeni jest możliwy dzięki:",a:["Fitochromom","Amyloplastom (statolitom), które opadają pod wpływem grawitacji i powodują nierównomierny rozkład auksyny","Chloroplastom","Rybosomom"],c:1,exp:"Amyloplasty (statolity) w czapeczce korzenia opadają pod wpływem grawitacji, wpływając na redystrybucję auksyny. Więcej auksyny po dolnej stronie hamuje wzrost korzenia, kierując go w dół."},
{id:102,rok:2025,cat:"Metabolizm",q:"Aktynidaza z owoców kiwi to proteaza, która:",a:["Rozkłada skrobię","Trawi białka - dlatego żelatyna nie żeluje po dodaniu świeżego kiwi","Rozkłada lipidy","Syntetyzuje białka"],c:1,exp:"Aktynidaza to proteaza cysteinowa z kiwi. Trawi żelatynę (białko kolagenowe), uniemożliwiając jej żelowanie - dlatego galaretka z kiwi nie tężeje."},
{id:103,rok:2025,cat:"Zoologia",q:"Rak szlachetny (Astacus astacus) jest zagrożony w Polsce głównie przez:",a:["Nadmierny połów","Konkurencję i dżumę raczą przenoszoną przez inwazyjnego raka pręgowatego","Zanieczyszczenie metalami ciężkimi","Ocieplenie klimatu"],c:1,exp:"Rak pręgowaty (inwazyjny gatunek z Ameryki) jest nosicielem Aphanomyces astaci (dżuma raków), na którą jest odporny, ale która zabija raka szlachetnego."},
{id:104,rok:2025,cat:"Fizjologia czlowieka",q:"Osłonka mielinowa neuronów przyspiesza przewodzenie impulsów dzięki:",a:["Ciągłemu przewodzeniu wzdłuż aksonu","Przewodzeniu skokowemu (saltatorycznemu) między przewężeniami Ranviera","Zwiększeniu średnicy aksonu","Zmniejszeniu oporności błony"],c:1,exp:"Mielina izoluje akson, a potencjał czynnościowy 'skacze' między odsłoniętymi przewężeniami Ranviera, co znacznie przyspiesza przewodzenie."},
{id:105,rok:2025,cat:"Fizjologia czlowieka",q:"Transportery GLUT2 w komórkach wątroby i beta trzustki NIE wymagają insuliny, ponieważ:",a:["Wątroba nie zużywa glukozy","GLUT2 mają niskie powinowactwo do glukozy i są konstytutywnie obecne w błonie, reagując na stężenie glukozy we krwi","GLUT2 są takie same jak GLUT4","Wątroba produkuje własną glukozę"],c:1,exp:"GLUT2 to transportery o niskim powinowactwie i dużej przepustowości, stale obecne w błonie. Wychwytują glukozę proporcjonalnie do jej stężenia we krwi - nie potrzebują sygnału insulinowego."},
{id:106,rok:2025,cat:"Genetyka",q:"Terapia celowana nowotworów za pomocą ADC (antibody-drug conjugate) polega na:",a:["Podaniu klasycznej chemioterapii","Połączeniu przeciwciała rozpoznającego antygen nowotworu z lekiem cytotoksycznym","Radioterapii","Usunięciu guza chirurgicznie"],c:1,exp:"ADC to przeciwciało skierowane przeciw antygenowi na komórkach nowotworowych, sprzężone z lekiem cytotoksycznym. Precyzyjnie dostarcza lek do komórek raka, zmniejszając działania uboczne."},
{id:107,rok:2025,cat:"Genetyka",q:"Rośliny transgeniczne otrzymuje się często z użyciem Agrobacterium tumefaciens, ponieważ:",a:["Bakteria ta naturalnie infekuje rośliny i wbudowuje fragment swojego DNA (T-DNA) w genom rośliny","Bakteria produkuje hormony roślinne","Bakteria tworzy mikoryzę z korzeniami","Bakteria chroni rośliny przed wirusami"],c:0,exp:"Agrobacterium naturalnie przenosi T-DNA z plazmidu Ti do genomu rośliny. W inżynierii genetycznej gen docelowy wkleja się w T-DNA, a bakteria dostarcza go do komórek rośliny."},
{id:108,rok:2025,cat:"Genetyka",q:"Elektroforeza DNA pozwala odróżnić apoptozę od nekrozy, ponieważ:",a:["Apoptoza daje regularne fragmenty DNA (drabinka), a nekroza - losowy rozmaz","Nekroza nie degraduje DNA","Apoptoza nie wpływa na DNA","Obie dają ten sam wzór"],c:0,exp:"W apoptozie kaspazy aktywują endonukleazy, które tną DNA w regularnych odstępach (co ~180 bp - nukleosomy), dając 'drabinkę'. Nekroza powoduje chaotyczną degradację - rozmaz."},
{id:109,rok:2025,cat:"Ewolucja",q:"Konwergencja ewolucyjna u roślin poduszkowych wysokogórskich polega na:",a:["Dziedziczeniu cechy od wspólnego przodka","Niezależnym wykształceniu podobnej formy wzrostu (zwartej poduszki) u niespokrewnionych gatunków w podobnych warunkach","Hybrydyzacji między gatunkami","Mutacjach w tym samym genie"],c:1,exp:"Rośliny poduszkowe niezależnie ewoluowały w różnych pasmach górskich (Andy, Alpy, Himalaje) - zwarta forma chroni przed wiatrem, zimnem i UV."},
{id:110,rok:2025,cat:"Ekologia",q:"Reintrodukcja zagrożonego gatunku (np. szpaka balijskiego) wymaga dbałości o różnorodność genetyczną populacji, ponieważ:",a:["Większa zmienność genetyczna daje większą szansę adaptacji do zmiennych warunków","Wszystkie osobniki muszą być identyczne genetycznie","Różnorodność genetyczna nie ma znaczenia","Reintrodukcja wymaga tylko jednej pary osobników"],c:0,exp:"Niska zmienność genetyczna (efekt wąskiego gardła) zwiększa podatność na choroby i ogranicza zdolność adaptacji - dlatego programy hodowlane dbają o różnorodność."}
];

const pytaniaOtwarte = [
// ===== CYTOLOGIA =====
{id:1,rok:2015,cat:"Cytologia",pkt:2,q:"Wyjaśnij, dlaczego mitochondria uznaje się za organella półautonomiczne. W odpowiedzi odnieś się do budowy mitochondriów.",ans:"Mitochondria mają własne koliste DNA oraz rybosomy 70S, dzięki czemu mogą samodzielnie syntetyzować część swoich białek. Jednak większość białek mitochondrialnych jest kodowana przez DNA jądrowe i importowana z cytoplazmy, dlatego nie są w pełni autonomiczne."},
{id:2,rok:2016,cat:"Cytologia",pkt:2,q:"Na schemacie przedstawiono budowę błony komórkowej. Wyjaśnij, dlaczego białka integralne mogą pełnić funkcję kanałów transportowych, a fosfolipidy tworzą barierę dla substancji polarnych.",ans:"Białka integralne przechodzą przez całą grubość dwuwarstwy i mogą tworzyć hydrofilowe kanały wewnątrz cząsteczki, umożliwiając transport jonów i cząsteczek polarnych. Fosfolipidy mają hydrofobowe ogony kwasów tłuszczowych skierowane do wewnątrz dwuwarstwy, co tworzy barierę nieprzepuszczalną dla substancji polarnych."},
{id:3,rok:2020,cat:"Cytologia",pkt:3,q:"Porównaj transport aktywny i bierny przez błonę komórkową. Uwzględnij: kierunek transportu względem gradientu stężeń, zapotrzebowanie energetyczne oraz podaj po jednym przykładzie każdego typu.",ans:"Transport bierny: zgodnie z gradientem stężeń, nie wymaga energii (ATP), np. osmoza, dyfuzja prosta. Transport aktywny: wbrew gradientowi stężeń, wymaga nakładu energii (ATP), np. pompa sodowo-potasowa (Na+/K+-ATPaza)."},

// ===== GENETYKA =====
{id:4,rok:2015,cat:"Genetyka",pkt:3,q:"Czynnik Rh jest dziedziczony jako cecha autosomalna dominująca. Kobieta Rh+ i mężczyzna Rh+ mają dziecko Rh-. Podaj genotypy rodziców i zapisz krzyżówkę genetyczną. Określ prawdopodobieństwo, że kolejne dziecko będzie Rh+.",ans:"Genotypy rodziców: matka Rr × ojciec Rr (oboje heterozygoty, bo mają dziecko rr).\nKrzyżówka: Rr × Rr → 1/4 RR : 2/4 Rr : 1/4 rr.\nPrawdopodobieństwo Rh+ u kolejnego dziecka = 3/4 (75%)."},
{id:5,rok:2017,cat:"Genetyka",pkt:5,q:"Fenyloketonuria (PKU) jest chorobą autosomalną recesywną. W populacji częstość allelu recesywnego (q) wynosi 0,02. Oblicz, korzystając z prawa Hardy'ego-Weinberga:\na) częstość nosicieli (heterozygot) w populacji,\nb) prawdopodobieństwo, że dwoje rodziców-nosicieli będzie miało chore dziecko.",ans:"a) q = 0,02, p = 1 - 0,02 = 0,98\nCzęstość nosicieli (2pq) = 2 × 0,98 × 0,02 = 0,0392 = ok. 3,92%\nb) Nosiciele: Aa × Aa → prawdopodobieństwo dziecka aa = 1/4 = 25%."},
{id:6,rok:2019,cat:"Genetyka",pkt:3,q:"Wyjaśnij, czym różni się regulacja operonu laktozowego (lac) od operonu tryptofanowego (trp) u E. coli. Uwzględnij rolę induktora i korepresora.",ans:"Operon lac jest regulowany przez indukcję - w nieobecności laktozy represor blokuje transkrypcję. Laktoza (induktor) wiąże się z represorem, zmieniając jego konformację i uwalniając od operatora, co umożliwia transkrypcję.\nOperon trp jest regulowany przez represję - represor sam nie wiąże się z operatorem. Gdy tryptofan (korepresor) połączy się z represorem, kompleks blokuje transkrypcję. Brak tryptofanu = transkrypcja aktywna."},
{id:7,rok:2021,cat:"Genetyka",pkt:2,q:"Wyjaśnij, na czym polega splicing i jakie jest jego biologiczne znaczenie. Podaj, które fragmenty pre-mRNA są usuwane.",ans:"Splicing to obróbka post-transkrypcyjna, polegająca na wycinaniu intronów (sekwencji niekodujących) z pre-mRNA i łączeniu eksonów (sekwencji kodujących) w dojrzały mRNA. Znaczenie: umożliwia alternatywny splicing - z jednego genu mogą powstać różne warianty białka poprzez różne kombinacje eksonów."},
{id:8,rok:2023,cat:"Genetyka",pkt:3,q:"U labradorów retriever barwa sierści zależy od dwóch genów: gen B (B - czarny pigment, b - brązowy) i gen E (E - odkładanie pigmentu, ee - brak odkładania = żółty). Zapisz krzyżówkę BbEe × bbEe i określ stosunek fenotypowy potomstwa.",ans:"Krzyżówka BbEe × bbEe:\nGen B: Bb × bb → 1/2 Bb : 1/2 bb\nGen E: Ee × Ee → 3/4 E_ : 1/4 ee\nFenotypy: czarny (B_E_) = 3/8, brązowy (bbE_) = 3/8, żółty (_ _ee) = 2/8\nStosunek: 3 czarne : 3 brązowe : 2 żółte."},
{id:9,rok:2024,cat:"Genetyka",pkt:4,q:"Choroby mitochondrialne są dziedziczone w linii matczynej. Wyjaśnij:\na) dlaczego te choroby są dziedziczone wyłącznie po matce,\nb) dlaczego objawy dotykają głównie mięśni, mózgu i serca,\nc) czym różni się ten typ dziedziczenia od dziedziczenia autosomalnego.",ans:"a) Mitochondria (i ich DNA) w zygocie pochodzą wyłącznie z komórki jajowej. Plemnik wnosi do zygoty głównie jądro, a jego nieliczne mitochondria są eliminowane.\nb) Mięśnie, mózg i serce mają najwyższe zapotrzebowanie na ATP. Mutacje mtDNA zaburzają fosforylację oksydacyjną, więc te tkanki są najbardziej poszkodowane.\nc) Dziedziczenie mitochondrialne nie podlega prawom Mendla, nie ma segregacji alleli, choroba jest przekazywana wyłącznie przez matkę wszystkim dzieciom."},

// ===== METABOLIZM / FIZJOLOGIA =====
{id:10,rok:2015,cat:"Metabolizm",pkt:3,q:"Porównaj chemiosmozę zachodzącą w mitochondriach i chloroplastach. Uwzględnij: miejsce tworzenia gradientu protonowego, kierunek przepływu H+ przez syntazę ATP oraz źródło energii napędzające pompowanie protonów.",ans:"Mitochondria: gradient H+ w przestrzeni międzybłonowej (między błonami), protony przepływają do matrix, energia pochodzi z utleniania NADH i FADH₂ w łańcuchu oddechowym.\nChloroplasty: gradient H+ wewnątrz tylakoidów (lumen), protony przepływają do stromy, energia pochodzi ze światła (transport elektronów w fazie jasnej fotosyntezy)."},
{id:11,rok:2018,cat:"Metabolizm",pkt:2,q:"Wyjaśnij mechanizm działania termogeniny (UCP1) w brunatnej tkance tłuszczowej i jego biologiczne znaczenie dla noworodków.",ans:"Termogenina jest białkiem rozprzęgającym w wewnętrznej błonie mitochondrialnej. Tworzy kanał dla protonów H+, które przepływają z przestrzeni międzybłonowej do matrix z pominięciem syntazy ATP. Energia gradientu jest rozpraszana jako ciepło zamiast być wykorzystana do syntezy ATP. U noworodków, które mają dużo brunatnej tkanki tłuszczowej, umożliwia to termogenezę bezdrżeniową - wytwarzanie ciepła bez drżenia mięśni."},
{id:12,rok:2016,cat:"Fizjologia czlowieka",pkt:3,q:"Na wykresie przedstawiono krzywą dysocjacji hemoglobiny. Wyjaśnij efekt Bohra i jego znaczenie dla wymiany gazowej w tkankach pracujących mięśni.",ans:"Efekt Bohra polega na zmniejszeniu powinowactwa hemoglobiny do tlenu przy obniżeniu pH (wzrost stężenia CO₂ i H+). W pracujących mięśniach: intensywne oddychanie komórkowe → dużo CO₂ → obniżenie pH → hemoglobina łatwiej oddaje O₂ tkankom. Dzięki temu tlen jest dostarczany preferencyjnie tam, gdzie jest najbardziej potrzebny."},
{id:13,rok:2019,cat:"Fizjologia czlowieka",pkt:2,q:"Wyjaśnij, dlaczego zatrucie tlenkiem węgla (CO) jest niebezpieczne. W odpowiedzi odnieś się do właściwości hemoglobiny.",ans:"CO ma ok. 200-250 razy większe powinowactwo do hemoglobiny niż O₂. Tworzy trwałe połączenie - karboksyhemoglobinę (HbCO), które blokuje miejsce wiązania tlenu. Nawet niewielka ilość CO skutecznie wyłącza dużą część hemoglobiny z transportu tlenu, prowadząc do niedotlenienia tkanek i potencjalnie do śmierci."},
{id:14,rok:2021,cat:"Fizjologia czlowieka",pkt:3,q:"Trzustka pełni funkcję zarówno gruczołu zewnątrzwydzielniczego, jak i wewnątrzwydzielniczego. Opisz obie funkcje, podając wydzielane substancje i ich rolę.",ans:"Funkcja zewnątrzwydzielnicza (egzokrynowa): trzustka wydziela sok trzustkowy do dwunastnicy zawierający enzymy trawienne - trypsynogen (trawienie białek), lipazę (trawienie tłuszczów), amylazę (trawienie skrobi) oraz NaHCO₃ (neutralizacja kwaśnej treści żołądkowej).\nFunkcja wewnątrzwydzielnicza (endokrynowa): wyspy Langerhansa wydzielają do krwi hormony - insulinę (komórki beta, obniża glukozę) i glukagon (komórki alfa, podnosi glukozę)."},

// ===== BOTANIKA =====
{id:15,rok:2016,cat:"Botanika",pkt:2,q:"Zaprojektuj doświadczenie badające wpływ auksyny na wydłużanie się odcinków koleoptyli owsa. Podaj próbę badaną, kontrolną i przewidywany wynik.",ans:"Próba badana: odcinki koleoptyli umieszczone w roztworze auksyny o znanym stężeniu.\nPróba kontrolna: odcinki koleoptyli umieszczone w wodzie destylowanej (bez auksyny).\nPrzewidywany wynik: odcinki w roztworze auksyny wydłużą się bardziej niż odcinki kontrolne, ponieważ auksyna stymuluje rozluźnianie ściany komórkowej i wzrost elongacyjny."},
{id:16,rok:2019,cat:"Botanika",pkt:2,q:"Wyjaśnij, w jaki sposób kwas abscysynowy (ABA) chroni roślinę przed utratą wody w warunkach suszy.",ans:"ABA (hormon stresu) jest syntetyzowany w zwiększonych ilościach podczas suszy. Powoduje zamykanie aparatów szparkowych poprzez wypływ jonów K+ i Cl- z komórek szparkowych, co prowadzi do spadku turgoru i zamknięcia szparki. Zamknięte szparki ograniczają transpirację (parowanie wody z liści), chroniąc roślinę przed odwodnieniem."},
{id:17,rok:2023,cat:"Botanika",pkt:3,q:"Porównaj fotosyntezę typu C3 i C4. Wyjaśnij, dlaczego rośliny C4 są wydajniejsze w gorącym i suchym klimacie.",ans:"C3: CO₂ wiązane bezpośrednio przez RuBisCO w cyklu Calvina, pierwszy produkt to 3-fosfoglicerynian (3C). Przy wysokiej temp. RuBisCO wiąże też O₂ (fotooddychanie), tracąc energię.\nC4: CO₂ wstępnie wiązane przez PEP-karboksylazę (nie reaguje z O₂) w komórkach mezofilu w kwas szczawiooctowy (4C). CO₂ uwalniane i zagęszczane w komórkach pochew wiązek, gdzie RuBisCO pracuje przy wysokim stężeniu CO₂, minimalizując fotooddychanie.\nW gorącym klimacie szparki są często zamknięte → mało CO₂ w liściu → u C3 dominuje fotooddychanie, u C4 mechanizm zagęszczania CO₂ eliminuje ten problem."},
{id:18,rok:2025,cat:"Botanika",pkt:2,q:"Wyjaśnij mechanizm percepcji grawitacji przez korzenie roślin (geotropizm dodatni). Uwzględnij rolę amyloplastów i auksyny.",ans:"W komórkach czapeczki korzenia znajdują się amyloplasty (statolity) wypełnione ziarnami skrobi. Pod wpływem grawitacji opadają na dolną stronę komórek, co jest sygnałem do redystrybucji auksyny. Auksyna gromadzi się po dolnej stronie korzenia. W korzeniach wysokie stężenie auksyny hamuje wzrost (w przeciwieństwie do łodyg), więc dolna strona rośnie wolniej niż górna, co powoduje zakrzywienie korzenia w dół (geotropizm dodatni)."},

// ===== EKOLOGIA =====
{id:19,rok:2017,cat:"Ekologia",pkt:2,q:"Wyjaśnij, dlaczego usunięcie gatunku zwornikowego (np. rozgwiazdy Pisaster) z ekosystemu prowadzi do spadku bioróżnorodności.",ans:"Gatunek zwornikowy kontroluje populację dominującego konkurenta (np. małży). Po usunięciu drapieżnika dominujący gatunek rozrasta się i wypiera inne gatunki w wyniku konkurencji o przestrzeń i zasoby. Efekt: spadek liczby gatunków, ekosystem staje się zdominowany przez jednego konkurenta."},
{id:20,rok:2020,cat:"Ekologia",pkt:3,q:"Wyspa Surtsey (Islandia) powstała w wyniku erupcji wulkanu w 1963 roku. Opisz przebieg sukcesji pierwotnej na tej wyspie, wymieniając kolejne etapy kolonizacji.",ans:"Etapy sukcesji pierwotnej na Surtsey:\n1. Kolonizacja nagiej lawy przez bakterie i sinice (pionierzy).\n2. Pojawienie się porostów i mszaków, które rozkruszają skałę i tworzą początkową glebę.\n3. Zasiedlenie przez rośliny zielne (trawy, byliny) przenoszone przez wiatr i ptaki morskie.\n4. Pojawienie się owadów i ptaków gniazdujących.\n5. Wzbogacanie gleby przez odchody ptaków (guano) → umożliwia wzrost kolejnych gatunków.\n6. Stopniowe zwiększanie się bioróżnorodności w kierunku biocenozy klimaksowej."},
{id:21,rok:2023,cat:"Ekologia",pkt:2,q:"Wyjaśnij, dlaczego murawy kserotermiczne wymagają ochrony czynnej. Podaj przykład działania ochronnego.",ans:"Murawy kserotermiczne to zbiorowiska półnaturalne, utrzymywane historycznie przez wypas zwierząt. Bez ingerencji człowieka zachodzi sukcesja wtórna - murawy zarastają krzewami i drzewami, co prowadzi do zaniku światłolubnych gatunków ciepłolubnych.\nPrzykład ochrony czynnej: kontrolowany wypas owiec lub kóz, koszenie, usuwanie nalotu drzew i krzewów."},

// ===== EWOLUCJA =====
{id:22,rok:2017,cat:"Ewolucja",pkt:2,q:"Wyjaśnij różnicę między grupą monofiletyczną a parafiletyczną w systematyce organizmów. Podaj przykład grupy parafiletycznej.",ans:"Grupa monofiletyczna (klad) obejmuje wspólnego przodka i WSZYSTKICH jego potomków - jest naturalną jednostką taksonomiczną.\nGrupa parafiletyczna obejmuje wspólnego przodka, ale NIE wszystkich jego potomków (część została wyłączona do innej grupy).\nPrzykład: gady (Reptilia) są grupą parafiletyczną, bo obejmują wspólnego przodka gadów i ssaków, ale wykluczają ptaki, które są potomkami dinozaurów (gadów)."},
{id:23,rok:2019,cat:"Ewolucja",pkt:2,q:"Wyjaśnij, czym jest specjacja allopatryczna. Podaj, jaki czynnik inicjuje ten proces, i opisz przykład.",ans:"Specjacja allopatryczna zachodzi, gdy populacja zostaje podzielona barierą geograficzną (np. góry, rzeka, ocean), uniemożliwiającą przepływ genów. Izolowane populacje ewoluują niezależnie pod wpływem różnych warunków środowiskowych, dryfu genetycznego i mutacji, aż powstają odrębne gatunki niezdolne do krzyżowania.\nPrzykład: karpieniec diabelski (Cyprinodon diabolis) - izolowana populacja ryb w jednym źródle w Nevadzie, która wyewoluowała w odrębny gatunek."},
{id:24,rok:2025,cat:"Ewolucja",pkt:3,q:"Rośliny poduszkowe występują w różnych pasmach górskich na świecie (Andy, Alpy, Himalaje) i należą do niespokrewnionych rodzin. Wyjaśnij, jaki proces ewolucyjny doprowadził do ich podobieństwa i podaj, jakie korzyści adaptacyjne daje forma poduszkowa.",ans:"Proces: konwergencja ewolucyjna - niezależne wykształcenie podobnych cech u niespokrewnionych gatunków pod wpływem podobnych warunków środowiskowych.\nKorzyści formy poduszkowej:\n- Ochrona przed silnym wiatrem (niska, zwarta forma)\n- Utrzymanie wyższej temperatury wewnątrz poduszki niż otoczenia\n- Zmniejszenie transpiracji i utraty wody\n- Ochrona przed intensywnym promieniowaniem UV na dużych wysokościach."},

// ===== DOŚWIADCZENIA / METODY =====
{id:25,rok:2018,cat:"Genetyka",pkt:2,q:"Wyjaśnij, dlaczego acetylacja histonów prowadzi do wzrostu ekspresji genów, a deacetylacja - do jej zahamowania.",ans:"Histony mają ładunek dodatni (reszty lizyny). DNA ma ładunek ujemny. Histony silnie wiążą DNA, tworząc skondensowaną chromatynę.\nAcetylacja: grupy acetylowe neutralizują ładunek dodatni histonów → osłabienie wiązania z DNA → rozluźnienie chromatyny (euchromatyna) → dostęp dla polimerazy RNA → transkrypcja aktywna.\nDeacetylacja: przywrócenie ładunku dodatniego → silne wiązanie DNA → kondensacja chromatyny (heterochromatyna) → brak dostępu → transkrypcja zahamowana."},
{id:26,rok:2023,cat:"Genetyka",pkt:3,q:"Opisz metodę PCR (łańcuchowej reakcji polimerazy). Wymień trzy etapy jednego cyklu PCR i podaj rolę starterów (primerów).",ans:"PCR to metoda powielania (amplifikacji) wybranego fragmentu DNA in vitro.\nTrzy etapy jednego cyklu:\n1. Denaturacja (~95°C) - rozdzielenie dwuniciowego DNA na pojedyncze nici.\n2. Przyłączanie starterów (~50-65°C) - komplementarne startery (primery) hybrydyzują do sekwencji flankujących amplifikowany fragment.\n3. Elongacja (~72°C) - polimeraza DNA (Taq) dobudowuje nowe nici od starterów.\nRola starterów: określają granice amplifikowanego fragmentu i dostarczają wolny koniec 3'-OH, od którego polimeraza DNA rozpoczyna syntezę nowej nici."},
{id:27,rok:2016,cat:"Metabolizm",pkt:2,q:"Metanol jest toksyczny, ponieważ dehydrogenaza alkoholowa przekształca go w formaldehyd. Wyjaśnij, dlaczego podanie etanolu jest leczeniem przy zatruciu metanolem. Określ typ inhibicji.",ans:"Etanol jest inhibitorem kompetycyjnym dehydrogenazy alkoholowej - konkuruje z metanolem o miejsce aktywne enzymu, ponieważ oba substraty mają podobną budowę. Gdy etanol zajmuje miejsce aktywne, metanol nie jest przekształcany w toksyczny formaldehyd i może być usunięty z organizmu przez nerki w formie niezmienionej. Typ inhibicji: kompetycyjna (odwracalna, zależna od stężenia inhibitora i substratu)."},
{id:28,rok:2020,cat:"Genetyka",pkt:2,q:"Wyjaśnij, na czym polega naprawa DNA przez wycinanie nukleotydów (NER) i dlaczego jest szczególnie ważna dla komórek skóry.",ans:"NER rozpoznaje zniekształcenia struktury podwójnej helisy DNA (np. dimery tyminowe powstałe pod wpływem promieniowania UV). Mechanizm: endonukleazy wycinają odcinek nici zawierający uszkodzenie, polimeraza DNA odtwarza brakujący fragment na matrycy nici komplementarnej, ligaza łączy nową nić z istniejącą.\nDla komórek skóry jest kluczowy, bo są one narażone na promieniowanie UV, które tworzy dimery tyminy. Defekt NER prowadzi do xeroderma pigmentosum - choroby o bardzo wysokim ryzyku nowotworów skóry."},

// ===== IMMUNOLOGIA =====
{id:29,rok:2018,cat:"Immunologia",pkt:3,q:"Choroba Gravesa-Basedowa jest chorobą autoimmunologiczną tarczycy. Wyjaśnij jej mechanizm, uwzględniając rolę przeciwciał i wpływ na poziom TSH.",ans:"W chorobie Gravesa układ odpornościowy produkuje przeciwciała skierowane przeciw receptorowi TSH na komórkach tarczycy. Przeciwciała te naśladują działanie TSH - stymulują receptor, powodując nadmierną produkcję hormonów tarczycy (T3 i T4).\nWysoki poziom T3/T4 w mechanizmie ujemnego sprzężenia zwrotnego hamuje wydzielanie TSH z przysadki → poziom TSH jest NISKI.\nObjawy: przyspieszone tętno, utrata masy ciała, wytrzeszcz oczu, nadmierna potliwość."},
{id:30,rok:2019,cat:"Immunologia",pkt:2,q:"Opisz budowę przeciwciała (immunoglobuliny). Wyjaśnij, jaka część cząsteczki odpowiada za wiązanie antygenu, a jaka za aktywację układu odpornościowego.",ans:"Przeciwciało ma kształt litery Y i składa się z 2 łańcuchów ciężkich (H) i 2 lekkich (L) połączonych wiązaniami disiarczkowymi.\nCzęść zmienna (Fab - fragment antigen-binding): końce ramion Y - tu znajdują się miejsca wiążące antygen. Każde przeciwciało ma 2 identyczne miejsca wiążące. Sekwencja aminokwasów jest zmienna, co zapewnia specyficzność wobec konkretnego antygenu.\nCzęść stała (Fc - fragment crystallizable): trzonek Y - odpowiada za aktywację dopełniacza, wiązanie przez receptory na makrofagach (opsonizacja) i określa klasę immunoglobuliny (IgG, IgM, IgA, IgE, IgD)."}
];

